### ISSUE TITLE
Beoordeling opdracht 1.2

### ISSUE THREAD

**Issue by chelseadoeleman** [robert-hoekstra/browser-technologies-1920#1]
Hi!

*Een beschrijving van alle features die je hebt getest*
Heel gaaf dat je eigen features hebt uitgekozen, die passen bij jou applicatie. Helaas ging het alleen bij deze opdracht over de acht features, die wij in de les hadden besproken. Als je dit zou kunnen aanvullen, kan ik er een voldoende van maken :) 

*Beschrijf hoe je de problemen hebt opgelost, of hoe je dit zou oplossen (met todo’s) als je genoeg tijd en budget zou hebben*
Zie hierboven... Moet dan helaas ook even geüpdatet worden. 

*Een beschrijving van de Devices en browsers waar je op hebt getest*
Heel uitgebreid! Lekker bezig! Vergeet niet de versie van de browser erbij te zetten. Ook heel nice, dat je hier gelijk oplossing voor hebt gegeven! 

*Een beschrijving van de screenreader test*
Ook een super uitgebreide beschrijving, met verbeterpunten!

**Comment by robert-hoekstra** [comment]
Hi Chelsea!
Thanks voor je issue/feedback. Wat stom van me dat ik de 8 features over het hoofd heb gezien. Ik heb de features aangevuld en beschreven met een oplossing. 

Hopelijk is het zo goed!

https://github.com/robert-hoekstra/browser-technologies-1920/blob/master/Opdracht1.2.md#chrome-8-features

**Comment by chelseadoeleman** [comment]
Hi Robert! 
Sorry voor de late reactie, maar ziet er super uit! 
Lekker bezig :)

**Comment by robert-hoekstra** [comment]
Thank you!
